### ISSUE TITLE
not compatible with Star Worm Equestrian

### ISSUE THREAD

**Issue by loander** [jusipat/astikor-carts#1]
Could we please have compatibility with Star Worm Equestrian mod (it recently got 1.20.1 build) ?https://www.curseforge.com/minecraft/mc-mods/swem

**Comment by jusipat** [comment]
I'm not familiar with this mod, would it not be possible to add the rideable entities you want added in the config file? I'll look into this asap

**Comment by loander** [comment]
Tried but did not work sadly

**Comment by jusipat** [comment]
After looking into it more, it seems to me the last time SWEMs was compatible with Astikor's was on version 1.16.5, I'll have to see what changed since then!

**Comment by jusipat** [comment]
Furthermore, the SWE mod github link seems to be broken, so I can't check in on there end regarding any past history of compat

**Comment by jusipat** [comment]
Unfortunately this looks like a dead end for now.
