### ISSUE TITLE
[REQUEST/BUG] Make carts not despawn completely with items when struck by lightning

### ISSUE THREAD

**Issue by mungasi2000** [jusipat/astikor-carts#13]
just had about 4 hours of loot wiped off the world by a single bolt of lightning, would be nice if carts were either immune or dropped all the items inside when hit by lightning

**Comment by jusipat** [comment]
Wow, I've never even thought of that. I will look into a fix for this.

**Comment by jusipat** [comment]
Fixed in 6a35954
