### ISSUE TITLE
mobs, animals, villagers move slow but game runs fine

### ISSUE THREAD

**Issue by kodytubegaming** [jusipat/astikor-carts#16]
plz fix this bug where my game runs well but when you encounter villagers, mobs, animals, etc they're slow especially when you hit them

**Comment by jusipat** [comment]
I cannot replicate this on my end. Please provide mod version, game version, and logs.

**Comment by kodytubegaming** [comment]
1.20.1 game version 
![image](https://github.com/user-attachments/assets/0
![image](https://github.com/user-attachments/assets/0271c10b-f6b1-40fe-b228-2b8948450880)
[2024-08-06-3.log.gz](https://github.com/user-attachments/files/16518562/2024-08-06-3.log.gz)
[latest.log](https://github.com/user-attachments/files/16518563/latest.log)
4745b39-5bbd-400c-b0f0-fdb7e047a23a)

**Comment by kodytubegaming** [comment]
it did the glitch after i went to sleep

**Comment by jusipat** [comment]
> 1.20.1 game version ![image](https://github.com/user-attachments/assets/0 ![image](https://private-user-images.githubusercontent.com/26213298/355684367-0271c10b-f6b1-40fe-b228-2b8948450880.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNzI4ODUsIm5iZiI6MTcyMzA3MjU4NSwicGF0aCI6Ii8yNjIxMzI5OC8zNTU2ODQzNjctMDI3MWMxMGItZjZiMS00MGZlLWIyMjgtMmI4OTQ4NDUwODgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDIzMTYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlY2M5ODcwYmFkYzYyZGY0YTUzNDE5Mzc0ZTMzOTE4NWE1NWJhYzkzMTRiMDgxYTc2YzM3M2VhMmU2OGI0YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wvqFEzp0_Bb1EF7qmhdX-gMG13XI3g4Z00AmnoLTcGU) [2024-08-06-3.log.gz](https://github.com/user-attachments/files/16518562/2024-08-06-3.log.gz) [latest.log](https://github.com/user-attachments/files/16518563/latest.log) 4745b39-5bbd-400c-b0f0-fdb7e047a23a)

This is not my mod. Please report to the relevant bug trackers. Closing.
