### ISSUE TITLE
[Request] Make it possible to re-texture Carts

### ISSUE THREAD

**Issue by Mowzy-Graphics** [jusipat/astikor-carts#9]
Would it be possible to make it so that the models and textures for the carts can be changed with a resource pack ?

I'm not much of a developper, so i don't know if this would be easy to introduce, but i'd love to make custom models and textures for carts, maybe even be able to switch up the textures and models using custom NBT. 

Carts in the style of the Create mod, that use brass and flywheels as wheels would be AMAZING !

**Comment by jusipat** [comment]
This is a great idea! I will certainly add it to the todo list, I unfortunately have had very little time to maintain the fork recently, though I will look into this as soon as I can!
